# Importing Modules

In [31]:
import numpy as np
import pandas as pd
import ast

In [32]:
credits=pd.read_csv('tmdb_5000_credits.csv')
movies=pd.read_csv('tmdb_5000_movies.csv')

In [33]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [34]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [35]:
movies_df=movies.copy()

# Merging movies and credits Datasets

In [36]:
movies_df=movies_df.merge(credits,on='title')
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [37]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

# Feature Selection

In [38]:
movies_df= movies_df[['id','genres','keywords','overview','title','cast','crew']]
movies_df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Data Preprocessing

In [39]:
movies_df.isna().sum()

id          0
genres      0
keywords    0
overview    3
title       0
cast        0
crew        0
dtype: int64

In [40]:
movies_df.dropna(inplace=True)

In [41]:
movies_df.duplicated().sum()

0

In [42]:
# Function to handel genres
def convert(text):
    genres=[]
    for i in ast.literal_eval(text):
        genres.append(i['name'])
    return genres

In [43]:
movies_df['genres']=movies_df['genres'].apply(convert)

In [44]:
movies_df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [45]:
movies_df['keywords']=movies_df['keywords'].apply(convert)

In [46]:
movies_df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [47]:
def FetchCast(text):
    
    cast=[]
    counter=0
    for i in ast.literal_eval(text):
        if counter!=5:
            cast.append(i['character'])
            counter+=1
            break
    return cast

In [48]:
movies_df['cast']=movies_df['cast'].apply(FetchCast)

In [49]:
movies_df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,[Jake Sully],"[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,[Captain Jack Sparrow],"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre,[James Bond],"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,[Bruce Wayne / Batman],"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,[John Carter],"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [50]:
def FetchDirector(text):
    
    director=[]
    for i in ast.literal_eval(text):
        if i['job']=='Director':
            director.append(i['name'])
            break
    return director

In [51]:
movies_df['crew']=movies_df['crew'].apply(FetchDirector)

In [52]:
movies_df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,[Jake Sully],[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,[Captain Jack Sparrow],[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre,[James Bond],[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,[Bruce Wayne / Batman],[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,[John Carter],[Andrew Stanton]

In [53]:
movies_df['overview']=movies_df['overview'].apply(lambda x:x.split())

In [54]:
movies_df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[Jake Sully],[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[Captain Jack Sparrow],[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[James Bond],[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[Bruce Wayne / Batman],[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,[John Carter],[Andrew Stanton]

In [55]:
movies_df['genres']=movies_df['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies_df['keywords']=movies_df['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies_df['cast']=movies_df['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies_df['crew']=movies_df['crew'].apply(lambda x: [i.replace(" ","") for i in x])

In [56]:
movies_df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[JakeSully],[JamesCameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[CaptainJackSparrow],[GoreVerbinski]
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[JamesBond],[SamMendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[BruceWayne/Batman],[ChristopherNolan]
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,[JohnCarter],[AndrewStanton]

In [57]:
movies_df['tags']= movies_df['overview'] + movies_df['genres'] + movies_df['keywords'] + movies_df['cast'] + movies_df['crew']

In [58]:
movies_df.head()

,id,genres,keywords,overview,title,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[JakeSully],[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[CaptainJackSparrow],[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[JamesBond],[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[BruceWayne/Batman],[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,[JohnCarter],[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [59]:
new_df=movies_df.copy()

In [61]:
new_df=new_df[['id','title','tags']]

In [62]:
new_df

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [63]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\91735\AppData\Local\Temp\ipykernel_18388\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [64]:
new_df.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [65]:
new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

C:\Users\91735\AppData\Local\Temp\ipykernel_18388\2543325826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

In [66]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

# Vectorization of text to numbers

In [67]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words="english")

In [68]:
vectors=cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [152]:
cv.get_feature_names_out()[0:1000]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '18', '18th', '19', '1930s', '1940s', '1944', '1950',
       '1950s', '1960s', '1970s', '1971', '1974', '1976', '1980', '1980s',
       '1985', '1990s', '1999', '19th', '19thcentury', '20', '200',
       '2003', '2009', '20th', '21st', '24', '25', '30', '300', '3d',
       '40', '50', '500', '60', '60s', '70', '70s', 'aaron', 'abandoned',
       'abducted', 'abilities', 'ability', 'able', 'aboard', 'abuse',
       'abusive', 'academy', 'accept', 'accepted', 'accepts', 'access',
       'accident', 'accidental', 'accidentally', 'accompanied',
       'accomplish', 'account', 'accountant', 'accused', 'ace', 'achieve',
       'act', 'acting', 'action', 'actionhero', 'actions', 'activist',
       'activities', 'activity', 'actor', 'actors', 'actress', 'acts',
       'actual', 'actually', 'adam', 'adams', 'adamshankman',
       'adaptation', 'adapted', 'addict', 'addicted', 'addiction',
       'adolescence', 'adolescent', 'adopt', 'adopted', 'adoption',
       'adopts', 'adult', 'adultanimation', 'adultery', 'adulthood',
       'adults', 'advantage', 'adventure', 'adventures', 'advertising',
       'advice', 'affair', 'affairs', 'affect', 'affection', 'affections',
       'afghanistan', 'africa', 'african', 'africanamerican',
       'aftercreditsstinger', 'afterlife', 'aftermath', 'age', 'aged',
       'agedifference', 'agency', 'agenda', 'agent', 'agents',
       'aggressive', 'aging', 'ago', 'agree', 'agrees', 'ahead', 'aid',
       'aided', 'aids', 'ailing', 'air', 'airplane', 'airplanecrash',
       'airport', 'aka', 'al', 'alabama', 'alan', 'alaska', 'albert',
       'alcatraz', 'alcohol', 'alcoholic', 'alcoholism', 'alex',
       'alexander', 'alfredhitchcock', 'ali', 'alice', 'alien',
       'alieninvasion', 'alienlife', 'alienplanet', 'aliens', 'alike',
       'alive', 'allen', 'alliance', 'allied', 'allies', 'allow',
       'allowing', 'allows', 'ally', 'alongside', 'alpha', 'alter',
       'alternate', 'alternative', 'alyssa', 'alzheimer', 'amanda',
       'amateur', 'amazing', 'amazon', 'ambassador', 'ambition',
       'ambitious', 'ambulance', 'ambush', 'america', 'american',
       'americanabroad', 'americancivilwar', 'americanfootball',
       'americanfootballplayer', 'americans', 'amid', 'amidst', 'amnesia',
       'amp', 'amsterdam', 'amusement', 'amusementpark', 'amy', 'ana',
       'anakin', 'analyst', 'anarchiccomedy', 'ancient', 'ancientrome',
       'ancientworld', 'anderson', 'andrew', 'android', 'andy', 'angel',
       'angela', 'angeles', 'angels', 'anger', 'anglee', 'angry',
       'animal', 'animalattack', 'animalhorror', 'animals', 'animated',
       'animation', 'anime', 'ann', 'anna', 'annabelle', 'anne', 'annie',
       'anniversary', 'announces', 'annual', 'anonymity', 'answer',
       'answers', 'ant', 'antarctic', 'anthology', 'anthony',
       'anthropomorphism', 'anti', 'antics', 'antihero', 'antoinefuqua',
       'apart', 'apartheid', 'apartment', 'ape', 'apes', 'apocalypse',
       'apocalyptic', 'apparent', 'apparently', 'appear', 'appears',
       'apple', 'appointed', 'apprentice', 'approach', 'approaches',
       'approaching', 'april', 'aquarium', 'arab', 'arch',
       'archaeologist', 'archeology', 'archer', 'architect', 'arctic',
       'area', 'aren', 'arena', 'argument', 'arise', 'aristocrat',
       'armed', 'arms', 'army', 'arnold', 'arrangedmarriage',
       'arrangement', 'arrest', 'arrested', 'arrival', 'arrive',
       'arrived', 'arrives', 'arriving', 'arrogant', 'art', 'arthur',
       'article', 'artificial', 'artificialintelligence', 'artist',
       'artistic', 'artists', 'arts', 'ash', 'ashes', 'ashley', 'asia',
       'asian', 'aside', 'ask', 'asked', 'asking', 'asks', 'aspirations',
       'aspiring', 'assassin', 'assassinate', 'assassination',
       'assassins', 'assault', 'assigned', 'assignment', 'assist',
       'assistant', 'assumes', 'asteroid', 'astronaut', 'astronauts',
       'asylum', 'atheist', 'athlete', 'atlantic', 'atomicbomb', 'attack',
       'attacked', 'attacks', 'attempt', 'attempting', 'attempts',
       'attempttoescape', 'attending', 'attends', 'attention', 'attic',
       'attitude', 'attorney', 'attracted', 'attraction', 'attractive',
       'audience', 'audiences', 'audition', 'august', 'aunt', 'austin',
       'australia', 'australian', 'author', 'authorities', 'authority',
       'autism', 'auto', 'automobileracing', 'avenge', 'average', 'avoid',
       'awaits', 'awakens', 'award', 'away', 'awry', 'ax', 'babe', 'baby',
       'bachelor', 'backdrop', 'backed', 'background', 'backgrounds',
       'bad', 'badly', 'bag', 'bahamas', 'bail', 'baker', 'balance',
       'ball', 'ballet', 'baltimore', 'band', 'bandits', 'bangkok',
       'banished', 'bank', 'banker', 'bankrobber', 'bankrobbery', 'bar',
       'barely', 'bargained', 'barn', 'barney', 'baron', 'barry',
       'barrylevinson', 'barrysonnenfeld', 'bars', 'base', 'baseball',
       'based', 'basedoncomicbook', 'basedongraphicnovel', 'basedonnovel',
       'basedonplay', 'basedonstagemusical', 'basedontrueevents',
       'basedontruestory', 'basedontvseries', 'basedonvideogame',
       'basedonyoungadultnovel', 'basement', 'basketball', 'batman',
       'battle', 'battlefield', 'battles', 'battling', 'bay', 'beach',
       'bear', 'bears', 'beast', 'beasts', 'beat', 'beating', 'beatrice',
       'beautiful', 'beautifulwoman', 'beauty', 'becky',
       'becominganadult', 'bed', 'bedroom', 'bee', 'beer', 'befriends',
       'began', 'begin', 'beginning', 'begins', 'behavior', 'beings',
       'belief', 'beliefs', 'believe', 'believed', 'believes',
       'believing', 'bell', 'bella', 'belong', 'belongs', 'beloved',
       'ben', 'beneath', 'benjamin', 'bennett', 'bent', 'berlin', 'best',
       'bestfriend', 'bestfriendsinlove', 'bet', 'beth', 'betrayal',
       'betrayed', 'better', 'betty', 'beverly', 'bible', 'bid', 'big',
       'bigger', 'biggest', 'biker', 'bikers', 'bikini', 'billionaire',
       'billy', 'biography', 'bird', 'birth', 'birthday', 'bisexual',
       'bishop', 'bit', 'bite', 'bitter', 'bizarre', 'black',
       'blackmagic', 'blackmail', 'blackpeople', 'blacksmith', 'blade',
       'blake', 'blame', 'blind', 'bliss', 'blizzard', 'block', 'blonde',
       'blood', 'bloodsplatter', 'bloodthirsty', 'bloody', 'blow', 'blu',
       'blue', 'board', 'boarding', 'boardingschool', 'boat', 'bob',
       'bobby', 'bobbyfarrelly', 'bodies', 'body', 'bodyguard', 'bold',
       'bollywood', 'bomb', 'bombing', 'bond', 'bonds', 'bone', 'book',
       'books', 'border', 'bored', 'boredom', 'boring', 'born', 'boss',
       'boston', 'botched', 'bound', 'boundaries', 'bounty',
       'bountyhunter', 'bourne', 'box', 'boxer', 'boxing', 'boy',
       'boyfriend', 'boys', 'brad', 'brain', 'brand', 'brandon', 'brave',
       'bravery', 'brazil', 'brazilian', 'break', 'breakdown', 'breaking',
       'breaks', 'breast', 'brent', 'brettratner', 'brian',
       'briandepalma', 'bride', 'bridesmaid', 'bridge', 'brief', 'brien',
       'bright', 'brilliant', 'bring', 'bringing', 'brings', 'brink',
       'britain', 'british', 'britishsecretservice', 'broadway', 'broke',
       'broken', 'broker', 'bronx', 'brooklyn', 'brooks', 'broom',
       'brothel', 'brother', 'brotherbrotherrelationship', 'brothers',
       'brothersisterrelationship', 'brought', 'brown', 'bruce',
       'brucewayne', 'brutal', 'brutality', 'brutally', 'bryansinger',
       'buck', 'bud', 'buddies', 'buddy', 'buddycomedy', 'buddycop',
       'budget', 'build', 'building', 'builds', 'built', 'bully',
       'bullying', 'bumbling', 'bunny', 'burglar', 'buried', 'burns',
       'bus', 'bush', 'business', 'businessman', 'bust', 'busy', 'butch',
       'butler', 'butt', 'buy', 'buzz', 'cabin', 'caesar', 'cage',
       'cairo', 'cal', 'caleb', 'california', 'called', 'calling',
       'calls', 'calvin', 'camcorder', 'came', 'camera', 'cameraman',
       'cameras', 'camp', 'campaign', 'campbell', 'camping', 'campus',
       'canada', 'canadian', 'cancer', 'candidate', 'candy', 'canine',
       'cannibal', 'canuxploitation', 'capable', 'caper', 'capital',
       'capitalism', 'capt', 'captain', 'captive', 'capture', 'captured',
       'captures', 'car', 'caraccident', 'carchase', 'carcrash', 'card',
       'care', 'career', 'carefree', 'cares', 'caretaker', 'caribbean',
       'carjourney', 'carl', 'carmen', 'carnival', 'carol', 'carolina',
       'carrace', 'carrie', 'carry', 'carrying', 'cars', 'cartel',
       'carter', 'cartoon', 'case', 'cases', 'cash', 'casino', 'cast',
       'castle', 'cat', 'cataclysm', 'catastrophe', 'catch', 'catches',
       'catholic', 'catholicism', 'cattle', 'caught', 'cause', 'caused',
       'causes', 'causing', 'cavalry', 'cave', 'cavemen', 'celebrate',
       'celebrated', 'celebration', 'celebrity', 'cell', 'cellphone',
       'cemetery', 'center', 'centered', 'centers', 'central',
       'centuries', 'century', 'ceo', 'ceremony', 'certain', 'chad',
       'chain', 'chainsaw', 'challenge', 'challenged', 'challenges',
       'champion', 'championship', 'chance', 'change', 'changed',
       'changes', 'changing', 'chaos', 'chaotic', 'chapter', 'character',
       'characters', 'charge', 'charged', 'charismatic', 'charles',
       'charlie', 'charlotte', 'charm', 'charming', 'chase', 'chased',
       'chases', 'chauffeur', 'cheating', 'cheerleader', 'chef',
       'chemical', 'chicago', 'chicken', 'chief', 'child', 'childabuse',
       'childhero', 'childhood', 'childprodigy', 'children', 'chilling',
       'china', 'chinese', 'chip', 'chloe', 'chocolate', 'choice',
       'choices', 'choose', 'chosen', 'chris', 'chriscolumbus',
       'chrissie', 'christ', 'christian', 'christianity', 'christine',
       'christmas', 'christmasparty', 'christmastree', 'christopher',
       'christophernolan', 'chronicle', 'chronicles', 'chuck', 'church',
       'cia', 'cigarettesmoking', 'cinderella', 'cindy', 'cinema',
       'circle', 'circuit', 'circumstances', 'circus', 'cities',
       'citizens', 'city', 'civil', 'civilian', 'civilization',
       'civilwar', 'claim', 'claiming', 'claims', 'claire', 'clan',
       'clark', 'clash', 'class', 'classdifferences', 'classes',
       'classic', 'classmate', 'classmates', 'classroom', 'clay', 'clean',
       'clear', 'clerk', 'client', 'clients', 'climate', 'climbing',
       'clinteastwood', 'clique', 'clock', 'clone', 'cloning', 'close',
       'closed', 'closer', 'club', 'clubs', 'clue', 'clueless', 'clues',
       'clutches', 'coach', 'coast', 'cocaine', 'cocky', 'code', 'cody',
       'coffin', 'cohen', 'col', 'cold', 'coldwar', 'cole', 'colin',
       'collapse', 'collapses', 'colleague', 'colleagues', 'collect',
       'collection', 'collector', 'college', 'collide', 'collins',
       'collision', 'colombia', 'colonel', 'colony', 'color', 'colorado',
       'colorful', 'coma', 'combat', 'combination', 'combined', 'come',
       'comeback', 'comedian', 'comedic', 'comedy', 'comes', 'comet',
       'comfort', 'comic', 'comics', 'coming', 'comingofage', 'comingout',
       'command', 'commander', 'commercial', 'commit', 'commitment',
       'committed', 'common', 'communication', 'communist', 'community',
       'companion', 'company', 'compete', 'competing', 'competition',
       'competitive', 'complete', 'completely', 'complex', 'complicated',
       'complications', 'composer', 'computer', 'computervirus', 'conan',
       'concert', 'conclusion', 'condition', 'conditions', 'conductor',
       'confederate', 'confession', 'confidence', 'confident', 'conflict',
       'confront', 'confronted', 'confronts', 'confused', 'congress',
       'conman', 'connected', 'connecticut', 'connection', 'connections',
       'connects', 'conner', 'connie', 'connor', 'conquer', 'conrad',
       'conscience', 'consequences', 'conservative', 'considered',
       'conspiracy', 'conspire', 'constant', 'constantly', 'construction',
       'consumed', 'contact', 'contain', 'containing', 'contains',
       'contemporary', 'contend', 'contest', 'continue', 'continues',
       'continuing', 'contract', 'control', 'controlled', 'controlling',
       'controversial', 'convention', 'converge', 'convict', 'convicted',
       'convince', 'convinced', 'convinces', 'cook', 'cooking', 'cool',
       'cooper', 'cop', 'cope', 'cops'], dtype=object)

# Stemming

In [70]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [71]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [72]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\91735\AppData\Local\Temp\ipykernel_18388\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [73]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

# Checking Similarity of movies

In [74]:
from sklearn.metrics.pairwise import cosine_similarity

In [75]:
similarity=cosine_similarity(vectors)

In [76]:
similarity[0]

array([1.        , 0.09284767, 0.05986843, ..., 0.02457366, 0.02512595,
       0.        ])

In [159]:
def Recommender(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distance=similarity[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movie_list:
         print(new_df.iloc[i[0]].title)

In [160]:
Recommender('Batman')

Batman
Batman & Robin
The Dark Knight Rises
Batman Begins
Batman Returns